builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: >-
      -s -w
      -X main.version={{ .Version }}
      -X main.commit={{ .Commit }}
      -X main.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - trallnag/{{ .ProjectName }}:{{ .Version }}-amd64
      - trallnag/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - trallnag/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - trallnag/{{ .ProjectName }}:latest-arm64v8
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}

docker_manifests:
  - name_template: trallnag/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - trallnag/{{ .ProjectName }}:{{ .Version }}-amd64
      - trallnag/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: trallnag/{{ .ProjectName }}:latest
    image_templates:
      - trallnag/{{ .ProjectName }}:latest-amd64
      - trallnag/{{ .ProjectName }}:latest-arm64v8
