repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
      - id: golangci-lint

  # ----------------------------------------------------------------------------
  # Local

  # ----------------------------------------------------------------------------

exclude: |
  (?x)^(
    CHANGELOG.md|
    swagger-ui\/.*
  )$
