repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [--profile black]

  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.16"
    hooks:
      - id: mdformat
        args: [--wrap=80]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types_or: [json, yaml]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.51.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/trallnag/pre-commit-mirror-gofumpt
    rev: v0.4.0
    hooks:
      - id: gofumpt

exclude: |
  (?x)^(
    swagger-ui\/.*
  )$

ci:
  skip:
    # Why is golangci-lint being skipped? It is already run as part of the
    # lint job in the general ci workflow. So we can spare the effort here.
    - golangci-lint
  autofix_commit_msg: |
    ci(pre-commit): Apply hook auto fixes

    For more information, see <https://pre-commit.com> and <https://pre-commit.ci>.
  autoupdate_commit_msg: |
    ci(pre-commit): Apply hook rev updates

    For more information, see <https://pre-commit.com> and <https://pre-commit.ci>.
