#!/usr/bin/env bash

help() {
  cat << EOF
Wrapper for running shfmt.
EOF
}

case $1 in -h | --help | help) help && exit ;; esac

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/log.sh"

cd "$PROJECT_DIR" || exit 1

# ------------------------------------------------------------------------------

shfmt \
  --binary-next-line \
  --diff \
  --indent=2 \
  --list \
  --simplify \
  --space-redirects \
  --write \
  scripts/*
