name: ci

#
# Primary workflow for continues integration.
#

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [trunk]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true



      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
