name: golangci-lint

#
# Lint code with golangci-lint.
#
# - <https://golangci-lint.run>
# - <https://github.com/golangci/golangci-lint>
#
# Could be merged into the ci workflow.
#

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [trunk, dev]
  schedule:
    - cron: 1 6 8 * *

permissions:
  contents: read

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
