name: Pre-commit

#
# Run pre-commit hooks.
#
# - <https://pre-commit.ci/lite.html>
#
# Relies on pre-commit.ci lite to be configured with the repository. It works
# in combination with it. The GitHub app takes care of PRs and autoupgrades.
# This workflow runs pre-commit on push events.
#
# Actually I have figured out that pre-commit.ci also runs on push events to the
# master branch. So we are kind of redundant here at the moment. One alternative
# would be to only run hooks here that are not supported by the service.
#
# If I want to drop pre-commit.ci I can add pre-commit-ci/lite-action to this
# workflow and adjust the workflow to also run on PRs.

on:
  workflow_dispatch:
  push:
    branches: [master, dev]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
          python -m pip freeze --local

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

      # Why is golangci-lint being skipped? It is already run as part of the
      # lint job in the general ci workflow. So we can spare the effort here.
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always
        env:
          SKIP: golangci-lint
