name: Release

#
# Release a new version of this project.
#
# Make sure to prepare project for a new release (see docs for more).
#

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: trallnag
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract release version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Extract release notes
        run: task extract-notes

      - name: Build distribution
        run: task build-dist VERSION=${{ env.VERSION }}

      - name: Build & push images
        run: task build-buildx VERSION=${{ env.VERSION }} LATEST=true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: tmp/release.md
          files: |
            dist/sha256sums.txt
            dist/*.tar.gz
            dist/*.zip
